export const LOADING = "auth/loading"
export const SIGN_IN = "auth/signIn"
export const LOG_OUT = "auth/signOut"
export const ADD_WORDS_CHUNK = "words/addWordsChunk"
export const ADD_WORDS_GROUP = "words/addWordsGroup"
export const SET_USER_WORDS = "user/setWords"
export const ADD_WORD_TO_USER = "user/addWord"
export const SET_USER_SETTINGS = "user/setSettings"