export const SET_LEVEL = 'SET_LEVEL';
export const SET_GAME_STATUS = 'SET_GAME_STATUS';

export const SET_GAME_STATISTICS = {
  START: 'SET_GAME_STATISTICS.START',
  FINISHED: 'SET_GAME_STATISTICS.FINISHED',
  FAILED: 'SET_GAME_STATISTICS.FAILED'
};

export const RESET_GAME_STATISTICS = "RESET_GAME_STATISTICS";

export const GET_GAME_STATISTICS = {
  START: 'GET_GAME_STATISTICS.START',
  FINISHED: 'GET_GAME_STATISTICS.FINISHED',
  FAILED: 'GET_GAME_STATISTICS.FAILED'
};

